Repository qmk/qmk_configurator, pull requests merged in 2019-10, with the labels that each got.

#511 adds translation instructions
  src/i18n/readme.md
Labels: documentation

#481 Prettier cmd
  .eslintrc.js
  .travis.yml
  package.json
  src/scss/_qmk_colors.scss
  src/scss/gmk-abs.scss
  src/scss/pantone.scss
  src/scss/sp-abs.scss
  src/scss/sp-pbt.scss
Labels: enhancement

#515 Add nightmare default layout
  public/keymaps/nightmare_default.json
Labels: enhancement

#516 Add Spanish translation
  src/components/SettingsPanel.vue
  src/i18n/es/index.js
  src/i18n/es/potato.js
  src/i18n/es/print.js
  src/i18n/es/tester.js
  src/i18n/index.js
Labels: hacktoberfest, translation

#518 add env variable handling for API url
  .env
  .env.production
  src/store/modules/constants.js
Labels: breakingchange

#513 Updated German translation
  src/i18n/de/index.js
  src/i18n/de/potato.js
  src/i18n/de/print.js
  src/i18n/de/tester.js
Labels: translation

#521 Update i18n readme with dropdown instructions
  src/i18n/readme.md
Labels: documentation

#526 Fixed bug with spinner where text was appearing gray.
  src/scss/themes.scss
Labels: bug

#519 added Russian translation (partial)
  src/i18n/index.js
  src/i18n/ru/index.js
  src/i18n/ru/potato.js
  src/i18n/ru/print.js
  src/i18n/ru/tester.js
  src/store/modules/app/state.js
Labels: WIP, translation

#525 [Translation] Add Brazilian portuguese translation (partial)
  src/i18n/index.js
  src/i18n/pt-BR/index.js
  src/i18n/pt-BR/potato.js
  src/i18n/pt-BR/print.js
  src/i18n/pt-BR/tester.js
  src/store/modules/app/state.js
Labels: WIP, translation

#531 Added Polish translation
  src/i18n/index.js
  src/i18n/pl-PL/index.js
  src/i18n/pl-PL/potato.js
  src/i18n/pl-PL/print.js
  src/i18n/pl-PL/tester.js
  src/store/modules/app/state.js
Labels: WIP, translation

#533 Fix output bug when printing
  src/views/Print.vue
Labels: bug

#538 Feat: Add brightness up and down keycodes
  src/store/modules/keycodes/app-media-mouse.js
Labels: enhancement

#539 Add default keymap for akb/raine
  public/keymaps/akb_raine_default.json
Labels: keymap

#528 added Russian translation 2 (partial)
  src/i18n/ru/index.js
  src/i18n/ru/tester.js
Labels: translation

#550 Updated Keyboard Exclusion List: 2019-10-21
  src/jquery.js
Labels: enhancement

#549 [Keyboard]Add keyboard Naked48/60
  public/keymaps/naked48_rev1_default.json
  public/keymaps/naked60_rev1_default.json
Labels: keymap

#546 Add Bahasa Malaysia translation.
  src/i18n/index.js
  src/i18n/ms/index.js
  src/i18n/ms/potato.js
  src/i18n/ms/print.js
  src/i18n/ms/tester.js
  src/store/modules/app/state.js
Labels: translation

#552 Default keymaps for new sweet16 boards
  public/keymaps/1upkeyboards_sweet16_v1_default.json
  public/keymaps/1upkeyboards_sweet16_v2_promicro_default.json
  public/keymaps/1upkeyboards_sweet16_v2_proton_c_default.json
  src/jquery.js
Labels: keymap

#558 Fix some issues with french translation
  src/i18n/fr/index.js
  src/i18n/fr/potato.js
  src/i18n/fr/tester.js
Labels: translation

#557 Added Italian translation
  src/i18n/index.js
  src/i18n/it/index.js
  src/i18n/it/potato.js
  src/i18n/it/print.js
  src/i18n/it/tester.js
Labels: translation

#556 Greek translation
  src/i18n/gr/index.js
  src/i18n/gr/potato.js
  src/i18n/gr/print.js
  src/i18n/gr/tester.js
Labels: translation
