Repository qmk/qmk_configurator, pull requests merged in 2019-09, with the labels that each got.

#490 Add a more helpful when redis is failing
  src/components/StatusBar.vue
Labels: enhancement

#496 Add a helpful switch count to UI
  src/components/Main.vue
  src/store/modules/keymap.js
Labels: feature

#502 Fix keycount when clearing base layer
  src/components/Main.vue
  src/store/modules/app/getters.js
  src/store/modules/keymap.js
Labels: bug

#506 Fixes for Noxary 260 and KBDfans KBD67 Mk.II RGB
  public/keymaps/kbdfans_kbd67_mkiirgb_default.json
  public/keymaps/noxary_260_default.json
Labels: bug

#508 Doro67 fixes
  public/keymaps/doro67_multi_default.json
  public/keymaps/doro67_regular_default.json
  public/keymaps/doro67_rgb_default.json
Labels: bug

#500 Adding language selection
  src/components/SettingsPanel.vue
  src/i18n/en/index.js
  src/i18n/fr/index.js
  src/main.js
  src/store/modules/app/actions.js
  src/store/modules/app/mutations.js
Labels: enhancement
