Repository qmk/qmk_configurator, pull requests merged in 2019-08, with the labels that each got.

#451 Don't change model for invalid inputs
  src/components/LayerKey.vue
Labels: bug

#460 refactor of CI
  .travis.yml
Labels: refactor

#457 Color keycode deletion links to key legend color
  src/scss/themes.scss
Labels: enhancement

#469 Add Extended Space Cadet keys
  src/store/modules/keycodes/quantum.js
Labels: enhancement
