Repository qmk/qmk_configurator, pull requests merged in 2019-06, with the labels that each got.

#381 Fix security warnings by github
  package.json
  yarn.lock
Labels: bug

#383 I18n print
  src/i18n/en/index.js
  src/i18n/en/print.js
  src/views/Print.vue
Labels: enhancement

#382 Make content keys selectable
  src/components/BaseKey.vue
  src/components/ContainerKey.vue
  src/components/LayerContainerKey.vue
  src/store/modules/keymap.js
Labels: enhancement

#409 [tester] Add ISO layout
  src/components/BaseKeymap.vue
  src/components/VisualTesterKeymap.vue
  src/store/modules/tester.js
  src/store/modules/tester/codeToPos.js
  src/store/modules/tester/index.js
  src/store/modules/tester/layouts.js
  src/store/modules/tester/qmk.js
Labels: WIP, enhancement
